export const HOME_SMALL_BG = 'https://assets.ccbp.in/frontend/react-js/home-sm-bg.png'
export const HOME_LARGE_BG = 'https://assets.ccbp.in/frontend/react-js/home-lg-bg.png'
export const PROFILE_BG = 'https://assets.ccbp.in/frontend/react-js/profile-bg.png'
export const WEBSITE_LOGO = 'https://assets.ccbp.in/frontend/react-js/logo-img.png'
export const FAILURE_LOGO = 'https://assets.ccbp.in/frontend/react-js/failure-img.png'
export const NO_JOBS = 'https://assets.ccbp.in/frontend/react-js/no-jobs-img.png'
export const NOT_FOUND = 'https://assets.ccbp.in/frontend/react-js/jobby-app-not-found-img.png'